name: Create MOC-Oracle Package
on:
  push:
    tags:
      - "v*"
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: echo @coinfabrik:registry=https://npm.pkg.github.com >> .npmrc
      - run: echo @money-on-chain:registry=https://npm.pkg.github.com >> .npmrc
      - run: echo //npm.pkg.github.com/:_authToken=${{secrets.MOC_SC_SHARED}} >> .npmrc
      - run: echo always-auth=true >> .npmrc
      - run: npm ci
      - run: npm run test -- --network ganacheCore
      - run: npm run compile
      - run: rm -r .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
